config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blog_entries#index'
  resources :blog_entries, only: [:index, :create, :new] do
    resources :like, only: [:create]
    resources :blog_comments, only: [:create, :new] do
      resources :like, only: [:create]
    end
  end

end

app/models/blog_comment.rb
# == Schema Information
#
# Table name: blog_comments
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  blog_entry_id :integer
#  body          :text
#  created_at    :datetime
#  updated_at    :datetime
#

class BlogComment < ActiveRecord::Base
  self.table_name = "blog_comments"

  belongs_to :user
  belongs_to :blog_entry

  has_many :likes, as: :likeable
end

app/models/blog_entry.rb
# == Schema Information
#
# Table name: blog_entries
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  ip         :string
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#
# Indexes
#
#  index_blog_entries_on_user_id  (user_id)
#

class BlogEntry < ActiveRecord::Base
  self.table_name = "blog_entries"

  belongs_to :user

  has_many :blog_comments
  has_many :likes, as: :likeable

  def empty?
    title.blank? &&
    body.blank? &&
    ip.blank?
  end
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  likeable_id   :integer
#  likeable_type :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_likes_on_likeable_type_and_likeable_id  (likeable_type,likeable_id)
#  index_likes_on_user_id                        (user_id)
#

class Like < ActiveRecord::Base
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  display_name           :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_display_name          (display_name) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :display_name, presence: true, uniqueness: true

  has_many :blog_entries
  has_many :blog_comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :display_name
    devise_parameter_sanitizer.for(:account_update) << :display_name
  end

  def permission_denied
    render :file => "public/401.html", status: :unauthorized
  end

end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
  def new
    @comment = BlogComment.new
  end

  def create
    if user_signed_in?
      adjusted_params = blog_comments_params.merge!(blog_entry_id: params[:blog_entry_id])
      current_user.blog_comments.create(adjusted_params)

      redirect_to blog_entries_path
    else
      permission_denied
    end
  end

  private
  def blog_comments_params
    params.require(:blog_comment).permit(:body)
  end
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  def index
    # list blog entries
    @entries = BlogEntry.order(created_at: :desc)

    render :index
  end

  def new
    if user_signed_in?
      @entry = BlogEntry.new
    else
      permission_denied
    end
  end

  def create
    if user_signed_in?
      current_user.blog_entries.create(blog_entry_params)

      redirect_to action: "index"
    else
      permission_denied
    end
  end

  private
  def blog_entry_params
    params.require(:blog_entry).permit(:title, :body).merge({ip: request.remote_ip})
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    if user_signed_in?
      if (comment_id = params[:blog_comment_id])
        likeable_object = BlogComment.find(comment_id)
      elsif (entry_id = params[:blog_entry_id])
        likeable_object = BlogEntry.find(entry_id)
      end
      likeable_object.likes.create(user: current_user)
    else
      permission_denied
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_comments/new.html.erb
<div id="submission">
  <h2>Submit new comment to blog post</h2>
  <%= form_for(@comment, url: { action: :create }) do |f| %>

  <div class="field_group">
  <%= f.label(:body, "Write your comment here: ", class: "prompt") %>
  <%= f.text_area(:body, class: "response") %>
  </div>

  <%= f.submit %>

  <% end %>
</div>

app/views/blog_entries/index.html.erb
<h2>All blog posts</h2>
<div id="entry_list">
  <% @entries.each do |e| %>
  <div class="blog_entry">
    <div class="title"><%= e.title %></div>
    <div class="entry_body"><%= e.body %></div>
    <div class="blog_meta">
      Posted by <span class="name"><%= e.user.display_name %></span> on <span class="date"> <%= e.created_at.to_date %> at <span class="time"><%= e.created_at.strftime("%H:%m:%S") %></span>
    </div>
    <% e.blog_comments.each do |c| %>
      <div class="blog_comment">
        <div class="comment_body"><%= c.body %></div>
        <div class="comment_author"><%= c.user.display_name %></div>
      </div>
    <% end %>
    <div id="link">
      <%= link_to("Add Comment", new_blog_entry_blog_comment_path(e)) %>
    </div>
  </div>
    <% end %>
</div>

app/views/blog_entries/new.html.erb
<div id="submission">
  <h2>Submit new blog post</h2>
  <%= form_for(@entry, url: { action: :create }) do |f| %>

  <div class="field_group">
  <%= f.label(:title, "Enter title here: ", class: "prompt") %>
  <%= f.text_field(:title, class: "response") %>
  </div>

  <div class="field_group">
  <%= f.label(:body, "Write to your heart's content: ", class: "prompt") %>
  <%= f.text_area(:body, class: "response") %>
  </div>

  <%= f.submit %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogTestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "shared/navigation" %>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/shared/_navigation.html.erb
<div id='navigation'>
  <ul id='nav_list'>
    <li><%= link_to("Home", root_path) %></li>

    <% if user_signed_in? %>
    <li><%= link_to("New Entry", new_blog_entry_path ) %></li>
    <li><%= link_to("Profile", edit_user_registration_path) %></li>
    <li><%= link_to("Log Out", destroy_user_session_path, method: :delete) %></li>
    <% else %>
    <li><%= link_to("Sign Up", new_user_registration_path) %></li>
    <li><%= link_to("Log In", new_user_session_path) %></li>
    <% end %>


  </ul>